#include "lua_controller.h"
#include "lua.hpp"
#include "lauxlib.h"
#include "lualib.h"

#include <iostream>

using namespace std;

// The entry point generated by SWIG.
extern "C" {
  extern int luaopen_argos(lua_State *L);
}

LuaController::LuaController() :
  LuaState(luaL_newstate()),
  LuaSource("/Users/tc/Prog/Robots/Lua-Foraging/controllers/lua_controller/foraging_controller.lua")
{
  luaL_openlibs(LuaState);
  luaopen_argos(LuaState);
  if (luaL_loadfile(LuaState, LuaSource.c_str())) {
    cerr << "Error while loading Lua controller source:"
	 << endl
	 << lua_tostring(LuaState, -1)
	 << endl;
    // dumpLuaStack(LuaState);
  }
  else if (lua_pcall(LuaState, 0, 0, 0)) {
    cerr << "Error while initializing Lua controller:"
	 << endl
	 << lua_tostring(LuaState, -1)
	 << endl;
    // dumpLuaStack(LuaState);
  }
}

void LuaController::Init(TConfigurationNode& configurationNode) {
  CallLuaFunction("init", &configurationNode);
}

void LuaController::ControlStep() {
  CallLuaFunction("control_step");
}

void LuaController::Reset() {
  CallLuaFunction("reset");
}

void LuaController::Destroy() {
  CallLuaFunction("destroy");
}

/*
 * This statement notifies ARGoS of the existence of the controller.
 * It binds the class passed as first argument to the string passed as
 * second argument.  The string is then usable in the XML
 * configuration file to refer to this controller.  When ARGoS reads
 * that string in the XML file, it knows which controller class to
 * instantiate.  See also the XML configuration files for an example
 * of how this is used.
 */
REGISTER_CONTROLLER(LuaController, "lua_controller")
